class AppStrings {
  AppStrings._();

  static const newsFeed = "News Feed";
  static const categories = "Categories";
  static const shop = "Shop";
  static const community = "Community";
  static const orders = "Orders";
  static const address = "Address";
  static const cropCare = "Crop Care";
  static const bestOffer = "Best Offers";
  static const diagnoseDisease = "Diagnose Disease";
  static const contactExpertise = "Contact Expertise";
  static const rateUs = "Rate Us";
  static const recommendedProduct = "Recommended Products";
  static const our = "Our";
  static const bestProducts = "Best Product";
  static const bestDeal = "Best Deal";
  static const myOrder = "My Order";
  static const offerProduct = "Offer Product";
  static const cart = "Cart";
  static const apply = "Apply";
  static const subtotal = "Subtotal";
  static const taxAndFee = "Tax & Fees";
  static const delivery = "Delivery";
  static const total = "Total";
  static const addToCart = "Add TO Cart";
  static const buyNow = "Buy Now";
  static const myProfile = "My Profile";
  static const deliveryAddress = "Delivery Address";
  static const settings = "Settings";
  static const bookMark = "Bookmark";
  static const contactUs = "Contact Us";
  static const paymentMethod = "Payment Method";
  static const tryFarmily = "Try Farmily";
  static const submit = "Submit";
  static const goToHome = "Go to Home";
  static const logout = "Log communityOut";
  static const save = "Save";
  static const pay = "Pay";
  static const trackYourOrder = "Track Your Order";
  static const generateReceipt = "Generate Receipt";
  static const changePassword = "Change Password";
  static const about = "About";
  static const notification = "Notification";
  static const privacyAndPolicy = "Privacy & Policy";
  static const helpCenter = "Help Center";
  static const reportAProblem = "Report a problem";
  static const invite = "Invite Friends";
  static const thankYourForPurchace = "Thank You For Your Purchase";
  static const saveSetting = "Save Settings";
  static const generalNotification = "General Notifications";
  static const orderNotification = "Order Notifications";
  static const emailNotification = "Email Notifications";
  static const allowNotification = "Allow Notifications";
  static const thanksDoubt =
      "Thanks,We Will Rectify The Problem Very As Soon As Possible";
}
